export const RECEIVE_PRODUCTS = 'receive_products'
export const ADD_TO_CART = 'add_to_cart'
export const CHECKOUT_REQ = 'checkout_req'
export const CHECKOUT_SUCCESS = 'checkout_success'
export const CHECKOUT_FAILURE = 'checkout_failure'